# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171018_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtest', models.ImageField(upload_to='upload')),
            ],
        ),
    ]
