# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
